number_of_particles = 15000
number_of_data_points = 1000
dt = 0.0005
radius = 1.0
gravity = 0.0
restitution = 1.0
width = 512
height = 512
density_number_of_rows = 20
density_number_of_columns = 20
collisions = "naive"


# [spatial_hash]
# number_of_rows = 10
# number_of_columns = 10
