number_of_particles = 1000
number_of_data_points = 1000
dt = 0.001
radius = 5.0
gravity = -90.8
restitution = 0.6
width = 512
height = 512
density_number_of_rows = 20
density_number_of_columns = 20
collisions = "naive"


# [spatial_hash]
# number_of_rows = 10
# number_of_columns = 10
